services:
  - type: web
    name: ai-mood-chatbot
    runtime: python
    plan: free

    buildCommand: pip install -r requirements.txt

    startCommand: python -m streamlit run chatmodel/UIChatbot.py --server.port $PORT --server.address 0.0.0.0